name: NopCommerce
run-name: ${{ github.actor }} is testing out NopCommerce
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM using SSH key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo add-apt-repository -y ppa:dotnet/backports
            sudo apt-get update
            sudo apt-get install -y aspnetcore-runtime-9.0 nginx unzip

            sudo systemctl start nginx

            echo 'server {
              listen 80 default_server;
              listen [::]:80 default_server;
            
              server_name   nopCommerce.com;
            
              location / {
              proxy_pass         http://localhost:5000;
              proxy_http_version 1.1;
              proxy_set_header   Upgrade $http_upgrade;
              proxy_set_header   Connection keep-alive;
              proxy_set_header   Host $host;
              proxy_cache_bypass $http_upgrade;
              proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header   X-Forwarded-Proto $scheme;
              }
            }' | sudo tee /etc/nginx/sites-available/default > /dev/null

            sudo mkdir -p /var/www/nopCommerce
            cd /var/www/nopCommerce

            sudo wget https://github.com/nopSolutions/nopCommerce/releases/download/release-4.80.8/nopCommerce_4.80.8_NoSource_linux_x64.zip
            sudo unzip nopCommerce_4.80.8_NoSource_linux_x64.zip

            sudo mkdir -p bin logs

            cd ..
            sudo chgrp -R www-data nopCommerce/
            sudo chown -R www-data nopCommerce/

            echo '[Unit]
            Description=nopCommerce app running on Ubuntu
            
            [Service]
            WorkingDirectory=/var/www/nopCommerce
            ExecStart=/usr/bin/dotnet /var/www/nopCommerce/Nop.Web.dll
            Restart=always
            RestartSec=10
            KillSignal=SIGINT
            SyslogIdentifier=nopCommerce
            User=www-data
            Environment=ASPNETCORE_ENVIRONMENT=Production
            Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
            
            [Install]
            WantedBy=multi-user.target' | sudo tee /etc/systemd/system/nopCommerce.service > /dev/null

            sudo systemctl start nopCommerce.service


            sudo systemctl restart nginx
