name: Send Email Notification

on: workflow_dispatch

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Deliberate failure
        run: exit 1

  notify:
    needs: fail-job
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: testing github action smtp
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: Github Action Failed
          to: abdullatif.alghabbari@alareebict.com
          #from: ${{ secrets.EMAIL_USER }}
          from: aa.alghobary@gmail.com
          content_type: text/plain
          body: |
            GitHub Actions run failed for:
            - Repo: ${{ github.repository }}
            - Workflow: ${{ github.workflow }}
            - Commit: ${{ github.sha }}
            - Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
