on: push
name: Send Email Notification
uses: dawidd6/action-send-mail@v2
with:
    server_address: smtp.gmail.com
    server_port: 465
    username: ${{secrets.EMAIL_USER}}
    password: ${{secrets.EMAIL_PASS}}
    subject: Notification from Github Action
    body: Hello :) 
    to: abdullatif.alghabbari@alareebict.com
    from: ${{secrets.EMAIL_USER}}
