name: gmail testing

on: workflow_dispatch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set email body with pipeline info
        id: set_body
        run: |
          echo "body=Repository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nWorkflow: ${{ github.workflow }}\nRun ID: ${{ github.run_id }}\nEvent: ${{ github.event_name }}" >> $GITHUB_OUTPUT

      - name: Send email with pipeline info
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: GitHub Action Pipeline Notification
          body: ${{ steps.set_body.outputs.body }}
          to: abdullatif.alghabbari@alareebict.com
          from: ${{ secrets.EMAIL_USER }}
